# BY MB Knowledge Center - MkDocs Configuration
site_name: BY MB Knowledge Center
site_description: AI-Optimized Knowledge Management System for BY MB Consultancy
site_author: BY MB Consultancy Documentation Team
site_url: https://bymbcom.github.io/bymb-documentation/
docs_dir: '.'

# Repository
repo_name: bymbcom/bymb-documentation
repo_url: https://github.com/bymbcom/bymb-documentation
edit_uri: edit/main/s://github.com/bymbcom/bymb-documentation
edit_uri: edit/main/

# Theme
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
#  - pymdownx.emoji:
     # emoji_index: !!python/name:materialx.emoji.twemoji
     # emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

# Navigation Structure
nav:
  - Home: index.md
  - Company Information:
    - Company_Information/index.md
    - Company Profile (English): Company_Information/Company_Profile_English_v1.1_20250422.md
    - Company Profile (Arabic): Company_Information/Company_Profile_Arabic_v1.0_20250422.md
    - Company History: Company_Information/Company_History_Timeline_v1.0_20250422.md
    - Team Directory: Company_Information/Team_Members_Directory_v1.0_20250422.md
    - Business Hours: Company_Information/Business_Hours_Holidays_v1.0_20250422.md
  
  - AI Roles:
    - AI_Roles/index.md
    - Operations Director: AI_Roles/AI_Roles_OperationsDirector_v1.0_20250524.md
    - Support Bot: AI_Roles/AI_Roles_SupportBot_v1.0_20250524.md
    - Tech Bot: AI_Roles/AI_Roles_TechBot_v1.0_20250524.md
    - Odoo Bot: AI_Roles/AI_Roles_OdooBot_v1.0_20250524.md
  
  - Services:
    - Services/index.md
    - Professional Services: Services/Professional_Services_Catalog_v1.0_20250518.md
    - Service Packages: Services/Service_Packages_Deliverables_v1.0_20250518.md
    - Customer Success: Services/Customer_Success_Management_v1.0_20250506.md
    - Smart Solutions:
      - Services/Smart_Solutions/index.md
      - Smart Home Automation: Services/Smart_Solutions/Smart_Home_Automation_v1.0_20250426.md
      - Advanced Security: Services/Smart_Solutions/Advanced_Security_Systems_v1.0_20250426.md
      - Integrated Ecosystems: Services/Smart_Solutions/Integrated_Smart_Ecosystems_v1.0_20250426.md
    - Analytics & BI:
      - Services/Analytics_Business_Intelligence/index.md
    - Networking & Digital Transformation:
      - Services/Networking_Digital_Transformation/index.md
  
  - Products:
    - Products/index.md
    - Networking Products: Products/Networking_Products_v1.0_20250529.md
    - CCTV Solutions:
      - Products/CCTV/index.md
  
  - Policies:
    - Policies/index.md
  
  - Procedures:
    - Procedures/index.md
  
  - FAQ:
    - FAQ/index.md
    - General FAQ: FAQ/General_FAQ_v1.0_20250424.md
    - Analytics & BI FAQ: FAQ/Analytics_BI_FAQ_v1.0_20250424.md
    - Smart Solutions FAQ: FAQ/Smart_Solutions_FAQ_v1.0_20250424.md
    - Networking FAQ: FAQ/Networking_DT_FAQ_v1.0_20250424.md
    - Products FAQ: FAQ/Products_FAQ_v1.0_20250424.md
    - Support FAQ: FAQ/Support_Maintenance_FAQ_v1.0_20250424.md
  
  - Templates:
    - Templates/index.md
  
  - System Architecture:
    - System_Architecture/index.md
  
  - Technical Documentation:
    - Technical_Documentation/index.md
  
  - Decision Trees:
    - Decision_Trees/index.md
  
  - Approval Workflow:
    - Approval_Workflow/index.md
  
  - Style Guide:
    - Style_Guide/index.md

# Plugins
plugins:
  - search:
      lang: 
        - en
        - ar
#  - minify:
    #  minify_html: true

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bymbcom
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/bymb-consultancy
  generator: false

# Copyright
copyright: Copyright &copy; 2025 BY MB Consultancy. All rights reserved.
